### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by xiaohangDAD** [Arasple/TrChat#10]
1. "1.6"版本会屏蔽非玩家发送的信息
2.监听到的消息有一个多余的"&3"
![图片](https://user-images.githubusercontent.com/41426821/69899636-38feac00-13a4-11ea-84cb-68322dce0615.png)
![图片](https://user-images.githubusercontent.com/41426821/69899641-40be5080-13a4-11ea-8f7c-925b9012c446.png)
![图片](https://user-images.githubusercontent.com/41426821/69899654-7bc08400-13a4-11ea-9caf-72084d08fbe2.png)
![图片](https://user-images.githubusercontent.com/41426821/69899665-ad394f80-13a4-11ea-810b-773a75ef09d6.png)
![图片](https://user-images.githubusercontent.com/41426821/69899670-c510d380-13a4-11ea-8f4e-9620aec1dbe8.png)
![图片](https://user-images.githubusercontent.com/41426821/69899677-d528b300-13a4-11ea-9182-abe9d708a27f.png)
![图片](https://user-images.githubusercontent.com/41426821/69899680-e245a200-13a4-11ea-902c-cdce71149d45.png)
暂时发现这些,基本上都是屏蔽类的问题
希望作者发布前进行自测试

被残忍屏蔽掉的公告
![图片](https://user-images.githubusercontent.com/41426821/69899731-93e4d300-13a5-11ea-9ed8-7534c7ca8c94.png)

另外希望作者可以加入一个手动重载配置文件的指令

**Comment by Arasple** [comment]
我的锅，请稍等

**Comment by Arasple** [comment]
敏感词问题应该已经解决，请重启服务器自动更新词库
监听聊天的那个BUG下次更新会修复

**Comment by Arasple** [comment]
命令重载也将会支持

**Comment by xiaohangDAD** [comment]
有些还是会屏蔽,希望你可以弄一个配置项,用来控制是否开启全局屏蔽和只屏蔽玩家聊天信息
另外云屏蔽词库还要再筛选一下
