### ISSUE TITLE
私聊建议

### ISSUE THREAD

**Issue by xiaohangDAD** [Arasple/TrChat#13]
ess基础插件有一个/m的私聊,trchat有一个/msg
请问作者能不能把ess的私聊禁用,就是输入/m 却使用trchat的私聊功能
因为trchat的私聊功能比较强大有提醒,自定义等功能,而玩家们却经常用/m[懒]
因此浪费了一个好功能
![图片](https://user-images.githubusercontent.com/41426821/69908835-fb456600-142b-11ea-9659-7ec52af1b4ee.png)

下面这个插件可能会对您有帮助
这个插件替换了ess插件的tpa指令
https://gitee.com/BukkitPlugin/OptimizedTeleport

**Comment by Arasple** [comment]
下次更新加一个 /m 的别称
另外 Ess 本身的命令可以在其配置中禁用
