### ISSUE TITLE
云端词库白名单貌似无效

### ISSUE THREAD

**Issue by xiaohangDAD** [Arasple/TrChat#15]
不知道是不是我的操作问题
![图片](https://user-images.githubusercontent.com/41426821/70635174-6e41ae80-1c6e-11ea-8d3d-d0b6b560a132.png)
![图片](https://user-images.githubusercontent.com/41426821/70635206-7dc0f780-1c6e-11ea-99d6-0987db81c64c.png)

**Comment by Arasple** [comment]
Fixed
