### ISSUE TITLE
BUG:不支持dynmap

### ISSUE THREAD

**Issue by nidbCN** [Arasple/TrChat#34]
服务器核心 -Paper-1.15.2-b155（试了试spigot貌似都这样）
插件列表：
-trchat
-dynmap
触发条件：
使用trchat发送的信息无法显示在dynmap的网页上面（dynmap是一款动态地图插件，内部提供网页聊天功能）。trchat正常发送消息，但是dynmap上面没有显示。嘛，trchat写着支持JSON的，dynmap也支持JSON，不过并没有显示:D。请问trchat有相关设置吗？考虑在trchat-pro中支持dynmap吗？

**Comment by Arasple** [comment]
重复
https://github.com/Arasple/TrChat/issues/27
