### ISSUE TITLE
BUG：使用 %i 展示 存储物品过多的潜影盒 时造成所有玩家群体掉线

### ISSUE THREAD

**Issue by YouMing233** [Arasple/TrChat#36]
服务端核心：Paper-1618 1.12.2
触发条件：
玩家手持 存储物品过多的潜影盒 并用 %i 进行展示时，会导致所有玩家同一时刻集体掉线
服务端后台无报错，只有该玩家发出展示消息后所有玩家离开游戏的消息
初步认为是该潜影盒的NBT过长，导致展示出问题emm

**Comment by Arasple** [comment]
这个问题已经修复， 重新下载最新版本
