### ISSUE TITLE
Why config and message is english?

### ISSUE THREAD

**Issue by Creepercdn** [Arasple/TrChat#38]
i'm a chinese. why config and message is english? i can toggle message langguage in config, but config is still english.
can i toggle config langguage to chinese? or chinese docs for config.

**Comment by Creepercdn** [comment]
my bad english.

**Comment by WulaGuy** [comment]
兄弟插件配置里setting.yml里头把LOCALE-PRIORITY下头“- zh_CN“这放到最前面
作者国人
