### ISSUE TITLE
liunx(Ubuntu)的监听配置文件改动无效

### ISSUE THREAD

**Issue by xiaohangDAD** [Arasple/TrChat#5]
在Ubuntu系统上改动TrChat的配置文件不会提示
[TrChat] 监听到配置文件改动, 已自动载入相关配置等...
[TrChat] 成功载入聊天格式... [0 Ms]
但在Windows系统上的TrChat会提示并自动重载
Windows的截图
![图片](https://user-images.githubusercontent.com/41426821/68767072-0b52fc80-065b-11ea-9566-436c575de4bd.png)
LIunx的没有任何提示

**Comment by Arasple** [comment]
Linux 无提示，配置的改动保存后是否生效？

**Comment by xiaohangDAD** [comment]
没有生效

**Comment by Arasple** [comment]
Please provide more information
