### ISSUE TITLE
BUG:服务器重启不能聊天

### ISSUE THREAD

**Issue by xiaozhiyl** [Arasple/TrChat#7]
服务器核心：PaperSpigot-1.12
服务器每天定时自动重启 有时候重启完玩家不能聊天必须再重启服务器才能聊天 聊天的权限我是给了的 请问这是什么问题？

**Comment by Arasple** [comment]
重启的方式?

请勿使用 /reload confirm 等命令重启

**Comment by xiaozhiyl** [comment]
stop指令正常重启
