### ISSUE TITLE
管理员监听私聊问题

### ISSUE THREAD

**Issue by xiaohangDAD** [Arasple/TrChat#8]
开启/spy监听模式后
监听到的聊天信息是两遍
![图片](https://user-images.githubusercontent.com/41426821/69240575-b9205700-0bd7-11ea-8164-2aa2790241ff.png)
windows下的服务器没测试
我的服务器是liunx的

**Comment by Arasple** [comment]
你发给别人肯定给你提示一条的。监听别的玩家就不会出现两次

**Comment by xiaohangDAD** [comment]
你可能没看截图,我指的是[监听]后面的消息是两边
![图片](https://user-images.githubusercontent.com/41426821/69537409-024b1f00-0fbb-11ea-93ae-76ae0b23493a.png)
1.51未修复
